name: Upgrade Cosmos DB SDK

on:
  schedule:
  - cron: '0 6 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Upgrade Cosmos DB SDK
      run: dotnet add src/Cosmos.Abstractions.Container/Cosmos.Abstractions.Container.csproj package Microsoft.Azure.Cosmos
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal
